export const PURPLE = '#7C3AED';
export const FONT = "'JetBrains Mono', 'SF Mono', 'Fira Code', 'Cascadia Code', monospace";

export const themes = {
  dark: {
    id: 'dark',
    bg: '#0B0E14',
    panel: '#111620',
    panelAlt: '#0D1017',
    border: '#1E2533',
    borderStrong: '#2A3040',
    text: '#C5CDD9',
    textStrong: '#E5E7EB',
    muted: '#6B7280',
    muted2: '#4B5563',
    code: '#8B949E',
    inputBg: '#0B0E14',
    accent: PURPLE,
    accentSoft: '#A78BFA',
    danger: '#EF4444',
    dangerBg: '#EF444422',
    qaBg: '#FFFFFF',
    qaText: '#111827',
    qaBorder: '#E5E7EB',
    overlay: 'rgba(0,0,0,0.55)',
    modalBg: '#111620',
    tipBg: '#111827',
    tipText: '#F9FAFB',
  },
  light: {
    id: 'light',
    bg: '#F3F4F6',
    panel: '#FFFFFF',
    panelAlt: '#F9FAFB',
    border: '#E5E7EB',
    borderStrong: '#D1D5DB',
    text: '#4B5563',
    textStrong: '#111827',
    muted: '#6B7280',
    muted2: '#9CA3AF',
    code: '#6B7280',
    inputBg: '#FFFFFF',
    accent: PURPLE,
    accentSoft: '#6D28D9',
    danger: '#DC2626',
    dangerBg: '#FEE2E2',
    qaBg: '#FFFFFF',
    qaText: '#111827',
    qaBorder: '#D1D5DB',
    overlay: 'rgba(15,23,42,0.35)',
    modalBg: '#FFFFFF',
    tipBg: '#111827',
    tipText: '#F9FAFB',
  },
};

export function makeStyles(t) {
  return {
    label: {
      fontSize: 11,
      fontWeight: 600,
      color: t.muted,
      textTransform: 'uppercase',
      letterSpacing: '0.06em',
      display: 'block',
      marginBottom: 4,
    },
    input: {
      width: '100%',
      padding: '7px 10px',
      fontSize: 12,
      background: t.inputBg,
      border: `1px solid ${t.border}`,
      borderRadius: 4,
      color: t.textStrong,
      outline: 'none',
      fontFamily: FONT,
      boxSizing: 'border-box',
    },
    btnPrimary: {
      padding: '8px 16px',
      fontSize: 12,
      fontWeight: 600,
      borderRadius: 4,
      border: 'none',
      background: t.accent,
      color: '#fff',
      cursor: 'pointer',
      fontFamily: FONT,
    },
    btnDanger: {
      padding: '8px 16px',
      fontSize: 12,
      fontWeight: 600,
      borderRadius: 4,
      border: `1px solid ${t.danger}`,
      background: t.dangerBg,
      color: t.danger,
      cursor: 'pointer',
      fontFamily: FONT,
    },
    btnGhost: {
      padding: '6px 12px',
      fontSize: 11,
      borderRadius: 4,
      border: `1px solid ${t.borderStrong}`,
      background: 'transparent',
      color: t.muted,
      cursor: 'pointer',
      fontFamily: FONT,
    },
    btnQa: {
      width: '100%',
      padding: '7px 10px',
      fontSize: 11,
      fontWeight: 600,
      borderRadius: 4,
      border: `1px solid ${t.qaBorder}`,
      background: t.qaBg,
      color: t.qaText,
      cursor: 'pointer',
      fontFamily: FONT,
      boxShadow: t.id === 'light' ? '0 1px 2px rgba(0,0,0,0.04)' : 'none',
    },
    preset: {
      padding: '2px 8px',
      fontSize: 10,
      borderRadius: 3,
      border: `1px solid ${t.borderStrong}`,
      background: 'transparent',
      color: t.muted,
      cursor: 'pointer',
      fontFamily: FONT,
    },
    chip: (active) => ({
      flex: 1,
      padding: '6px 0',
      fontSize: 11,
      borderRadius: 4,
      border: `1px solid ${active ? t.accent : t.borderStrong}`,
      background: active ? `${t.accent}22` : 'transparent',
      color: active ? t.accentSoft : t.muted,
      cursor: 'pointer',
      fontFamily: FONT,
    }),
  };
}
